/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package clzola.pmnlgame.client.gui;

import clzola.pmnlgame.message.RoomMessages;
import java.awt.Color;
import javax.swing.JTextPane;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyleContext;
import javax.swing.text.StyledDocument;

/**
 *
 * @author clzola
 */
public class ChatPanel extends javax.swing.JPanel {
    private GameView view;
    
    /**
     * Creates new form ChatPanel
     */
    public ChatPanel(GameView v) {
        initComponents();
        this.view = v;
    }
    
    public void clearChat() {
        this.ChatArea.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Input = new javax.swing.JTextField();
        Send = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ChatArea = new javax.swing.JTextPane();

        setPreferredSize(new java.awt.Dimension(640, 135));
        setLayout(new java.awt.BorderLayout(4, 4));

        jPanel1.setLayout(new java.awt.BorderLayout(4, 4));

        Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputActionPerformed(evt);
            }
        });
        jPanel1.add(Input, java.awt.BorderLayout.CENTER);

        Send.setText("Send");
        Send.setPreferredSize(new java.awt.Dimension(92, 26));
        Send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendActionPerformed(evt);
            }
        });
        jPanel1.add(Send, java.awt.BorderLayout.LINE_END);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        ChatArea.setEditable(false);
        ChatArea.setFocusable(false);
        jScrollPane2.setViewportView(ChatArea);

        add(jScrollPane2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputActionPerformed
        if( Input.getText().trim().length() > 0 ) {
            RoomMessages.ChatMessage chatMessage = new RoomMessages.ChatMessage();
            chatMessage.info= false;
            chatMessage.chatMessage = Input.getText();
            view.client.sendTCP(chatMessage);
            this.Input.setText("");
        }
    }//GEN-LAST:event_InputActionPerformed

    private void SendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendActionPerformed
        if( Input.getText().trim().length() > 0 ) {
            RoomMessages.ChatMessage chatMessage = new RoomMessages.ChatMessage();
            chatMessage.info= false;
            chatMessage.chatMessage = Input.getText();
            view.client.sendTCP(chatMessage);
            this.Input.setText("");
        }
    }//GEN-LAST:event_SendActionPerformed

    public synchronized void addChatMessage(RoomMessages.ChatMessage message) {
        if( message.info ) {
            appendToPane(ChatArea, " *** " + message.chatMessage + "\n", Color.MAGENTA);
        } else {
            appendToPane(ChatArea, message.playerId, Color.BLUE);
            appendToPane(ChatArea, ": " + message.chatMessage + "\n", Color.BLACK);
        }
    }
    
    private void appendToPane(JTextPane tp, String msg, Color c)
    {
        StyledDocument doc = tp.getStyledDocument();

        Style style = tp.addStyle("I'm a Style", null);
        StyleConstants.setForeground(style, c);

        try { doc.insertString(doc.getLength(), msg,style); }
        catch (BadLocationException e){}
        
        ChatArea.select(doc.getLength(), doc.getLength());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane ChatArea;
    private javax.swing.JTextField Input;
    private javax.swing.JButton Send;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
